# Generated by Django 3.1.3 on 2020-11-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteladmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('contact', models.BigIntegerField()),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('categories', models.CharField(max_length=200, null=True)),
                ('hotelimage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('hotelimage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('hotelimage3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200, null=True)),
                ('sleeps', models.CharField(max_length=200, null=True)),
                ('room_price', models.FloatField()),
                ('room_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_available', models.IntegerField()),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
            ],
        ),
        migrations.CreateModel(
            name='Room_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free_wifi', models.BooleanField(blank=True, default=False, null=True)),
                ('king_size_bed', models.BooleanField(blank=True, default=False, null=True)),
                ('TV', models.BooleanField(blank=True, default=False, null=True)),
                ('Bath_Tube', models.BooleanField(blank=True, default=False, null=True)),
                ('Safe_box', models.BooleanField(blank=True, default=False, null=True)),
                ('Welcome_bottle', models.BooleanField(blank=True, default=False, null=True)),
                ('Breakfast', models.BooleanField(blank=True, default=False, null=True)),
                ('Lunch', models.BooleanField(blank=True, default=False, null=True)),
                ('Dinner', models.BooleanField(blank=True, default=False, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
            ],
        ),
    ]
