# Generated by Django 3.1.3 on 2020-11-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_features',
        ),
    ]
