# Generated by Django 3.1.2 on 2020-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladmin',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
