# Generated by Django 3.1.2 on 2020-11-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_auto_20201108_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladmin',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='description',
            field=models.TextField(default=0, max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='hotelimage1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hoteladmin',
            name='hotelimage2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, null=True)),
                ('room_description', models.TextField(max_length=1000, verbose_name='description')),
                ('room_type', models.CharField(max_length=200, null=True)),
                ('room_price', models.FloatField()),
                ('room_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('room_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
            ],
        ),
    ]
