# Generated by Django 3.1.3 on 2020-11-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_delete_room_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free_wifi', models.BooleanField(default=False)),
                ('king_size_bed', models.BooleanField(default=False)),
                ('TV', models.BooleanField(default=False)),
                ('Bath_Tube', models.BooleanField(default=False)),
                ('Safe_box', models.BooleanField(default=False)),
                ('Welcome_bottle', models.BooleanField(default=False)),
                ('Breakfast', models.BooleanField(default=False)),
                ('Lunch', models.BooleanField(default=False)),
                ('Dinner', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.rooms')),
            ],
        ),
    ]
