# Generated by Django 3.1.3 on 2020-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_room_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_features',
            name='Bath_Tube',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Breakfast',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Dinner',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Free_wifi',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Lunch',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Safe_box',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='TV',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='Welcome_bottle',
        ),
        migrations.RemoveField(
            model_name='room_features',
            name='king_size_bed',
        ),
        migrations.AddField(
            model_name='room_features',
            name='feature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
