# Generated by Django 3.1.3 on 2020-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_auto_20201114_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_features',
            name='feature',
        ),
        migrations.AddField(
            model_name='room_features',
            name='Bath_Tube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Safe_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='TV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='Welcome_bottle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_features',
            name='king_size_bed',
            field=models.BooleanField(default=False),
        ),
    ]
