# Generated by Django 3.1.2 on 2020-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_hoteladmin_hotelimage3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteladmin',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
