# Generated by Django 3.1.3 on 2020-11-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0005_auto_20201114_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.rooms')),
            ],
        ),
    ]
