# Generated by Django 3.1.3 on 2020-11-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0006_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='features',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hoteladmin',
            name='hotelimage2',
        ),
        migrations.RemoveField(
            model_name='hoteladmin',
            name='hotelimage3',
        ),
        migrations.AddField(
            model_name='features',
            name='Free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='features',
            name='Loundry_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='features',
            name='Parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='features',
            name='Restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='features',
            name='Swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Hotel_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin')),
            ],
        ),
    ]
