# Generated by Django 3.1.3 on 2020-11-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0010_auto_20201121_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
    ]
