# Generated by Django 3.1.3 on 2020-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0012_auto_20201121_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guest',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
