# Generated by Django 3.1.3 on 2020-11-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0013_booking_total_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
