# Generated by Django 3.1.3 on 2020-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0014_remove_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
