# Generated by Django 3.1.3 on 2020-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0016_auto_20201123_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
