# Generated by Django 3.1.3 on 2020-11-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0017_auto_20201127_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reff_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='refferd_user',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
