# Generated by Django 3.1.3 on 2020-11-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0018_auto_20201130_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='reffreal_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=225, null=True)),
                ('ref_discount', models.IntegerField(null=True)),
                ('ref_price', models.IntegerField(null=True)),
                ('referd_person_discount', models.IntegerField(null=True)),
                ('order_maximum', models.IntegerField(null=True)),
                ('ref_status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
