# Generated by Django 3.1.3 on 2020-12-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0020_reffreal_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn.hoteladmin'),
        ),
    ]
