# Generated by Django 3.1.3 on 2020-12-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0021_customer_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hotels',
        ),
    ]
