# Generated by Django 3.1.3 on 2020-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0022_remove_customer_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
